### ISSUE TITLE
Could ESP-32 be used instead of HC-05 and pro mini? 

### ISSUE THREAD

**Issue by Oxmaster** [RalphBacon/193-Smart-Phone-Charger#1]
I'm thinking about making this charge limiter, but simpler. I have not used bluetooth on arduino or ESP platforms so I want to ask if standalone ESP32 would work?

**Comment by RalphBacon** [comment]
The ESP32 certainly has BT built in - but I didn't go that route because I was familiar with HC-06/05 units and had plenty to use. But with some experimentation you should be able to use the BT in the ESP32 just the same - but don't ask me for advice because I have no experience with that aspect of the ESP32. I'm sure plenty of others have, though. Google will certainly be your Best Friend Forever!
